spring: 
  datasource:
    name: mybatis_plus
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.161.131:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&&serverTimezone=UTC
    username: root
    password: gu425006
    driver-class-name: com.mysql.cj.jdbc.Driver
   

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql

